[package]
name = "zkagent_starknet"
version = "0.1.0"
edition = "2023_10"


[dependencies]
starknet = ">=2.4.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.18.0" }

[dev-dependencies]

[tool.snforge]
